# Generated by Django 5.0 on 2023-12-08 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_employee_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Company Address')),
                ('zip_code', models.CharField(blank=True, max_length=250, verbose_name='Company Zip Code')),
                ('city', models.CharField(blank=True, max_length=250, verbose_name='Company City')),
                ('website', models.URLField(blank=True, verbose_name='Company Website')),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='Company Email')),
                ('phone', models.CharField(blank=True, max_length=250, verbose_name='Company Contact')),
            ],
            options={
                'db_table': 'partner_companies',
            },
        ),
        migrations.AddField(
            model_name='finishedbuilding',
            name='partner_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.partnercompany'),
        ),
    ]
